apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-irc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-irc
  template:
    metadata:
      labels:
        app: web-irc
    spec:
      containers:
        - name: web-irc
          image: 'hanivanrizky/web-irc:1.0.0'
          resources:
            requests:
              cpu: '250m'
              memory: '64Mi'
            limits:
              cpu: '500m'
              memory: '128Mi'
          ports:
            - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: web-irc
spec:
  type: LoadBalancer
  externalIPs:
    - 192.168.49.2
  selector:
    app: web-irc
  ports:
    - protocol: TCP
      name: main-port
      port: 3000
      targetPort: 3000
